module.exports = {
  port: '6786',
  databaseHost: 'localhost',
  databaseUser: 'root',
  databasePassword: '',
  databaseDatabaseName: 'commondb',
  emailVerifiedLink: 'http://localhost:4200/confirmEmail?token=',
  resetPasswordLink: 'http://localhost:4200/resetPassword?token=',
  tokenkey: '37LvPsm4vaBcd4CY',
  env: 'development',
  supportEmail: 'info@commonAPI.com',
  SMTPemailAddress: 'developers.winjit@gmail.com',
  SMTPPassword: 'Winjit@321',
  database_initial: 'common',
};
