module.exports = {
  tokenIssue: 'Improper token',
  tokenMissing: 'Please send token',
  success: 'Success',
  movedPermanently: 'The requested URL has moved to a new URL',
  found: 'The requested URL has moved temporarily to a new URL',
  seeOthers: 'The requested URL can be found under a different URL',
  notModifies:
    'The requested URL has not been modified since the specified date',
  temporaryRedirect: 'The requested URL has moved temporarily to a new URL',
  badRequest: 'Bad Request, request is made with invalid arguments',
  unAuthorized: 'Access token is missing or invalid',
  forbidden: 'Access to the requested URL is forbidden',
  notFound: 'The server can not find the requested URL',
  methodNotAllowed: 'The method specified in the request is not allowed',
  notAcceptable: 'Not Acceptable',
  preconditionFailed: 'Precondition Failed',
  unsupportedMediaType: 'Unsupported Media Type',
  internalServerError:
    'The request was not completed. The server met an unexpected condition',
  notImplemented:
    'The request was not completed. The server did not support the functionality required',
  connectionFailed:
    'The request was not completed. The server is temporarily overloading or down',
  dbError: 'Unable to process your request, please try again',
  sessionExpire: 'Session expires. Please login again',
  invalidDetails: 'Invalid details',
  tryCatch: 'Something went wrong. Please contact admin.',
  registration: 'Registration done successfully',
  invalidEmail: 'Please insert email address in correct format',
  invalidLoginDetails: 'Invalid login details',
  duplicateDetails: 'Email Address or mobile number already exists',
  emailVerify: 'Please complete email verification process',
  emailVerificationSuccess:
    'Email address successfully verified. Please login to continue',
  emailLinkExpired: 'Link has expired.',
  registrationEmailSubject: 'Welcome to CommonAPI',
  passwordChanged: 'Password changed successfully',
  invalidPassword: 'Password is not valid',
  forgotPasswordSubject: 'Common API, Forgot password link',
  resetLink:
    'Reset link sent successfully. You will receive a link shortly if a user is registered.',
  passwordReset: 'Password has been successfully reset. Please login',
  profileUpdate: 'Profile updated successfully',
  allFieldReq: 'Please fill all required fields',
  noData: 'No information available',
  duplicateUser: 'User details already exist',
  accountDisable:
    'Please contact admin. Your account has been deleted or blocked!',
  accountActivated: 'Account is activated',
  accountDeactivated: 'Account is deactivated',
  accountReactivated: 'Account is re-activated',
  sendingEmailFailed: 'Having some issue while sending email',
  invalidImage: 'Image type is not valid',
};
